# MoE-Stream: replacement OFF — baseline with same arch, no lifecycle management
model_type = 'moe_stream'
dataset = 'bytes'
batch_size = 1
block_size = 256
n_embd = 128
n_layer = 4
ssm_d_state = 8
ssm_d_conv = 4
ssm_expand = 2
n_predict = 4
n_experts = 4
top_k = 2
expert_hidden_mult = 4
dropout = 0.0
bias = False
importance_momentum = 0.99
replacement_threshold = -1        # Disabled: never replace
expert_min_tokens = 2000
moe_balance_coeff = 0.02
replace_experts_interval = 0      # Never trigger replacement loop
learning_rate = 6e-4
max_iters = 2000
weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95
grad_clip = 1.0
decay_lr = True
warmup_iters = 200
lr_decay_iters = 2000
min_lr = 6e-5
dtype = 'float32'
compile = False
eval_interval = 1000
log_interval = 10
always_save_checkpoint = False
out_dir = 'out_moe_stream_off'
