# MoE-Stream: 4L/128D, 4 experts, top-2 — first test
model_type = 'moe_stream'
dataset = 'bytes'
batch_size = 1
block_size = 256
n_embd = 128
n_layer = 4
ssm_d_state = 8
ssm_d_conv = 4
ssm_expand = 2
n_predict = 4
n_experts = 4
top_k = 2
expert_hidden_mult = 4
dropout = 0.0
bias = False
importance_momentum = 0.99       # Slightly lower for faster EMA adaptation
replacement_threshold = 0.05     # Global floor; per-layer adaptive threshold may be higher
expert_min_tokens = 2000         # Lower for small test (fewer tokens/step)
moe_balance_coeff = 0.02         # Slightly higher to offset gradient impact's sharper signal
replace_experts_interval = 400   # Check at step 400 and 800 within 1000-iter run
learning_rate = 6e-4
max_iters = 1000
weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95
grad_clip = 1.0
decay_lr = True
warmup_iters = 100
lr_decay_iters = 1000
min_lr = 6e-5
dtype = 'float32'
compile = False
eval_interval = 500
log_interval = 10
always_save_checkpoint = True
out_dir = 'out_moe_stream'
