# Stream: first light test — 4L/128D/block128 on bytes — with patcher + decayed loss
dataset = 'bytes'
batch_size = 1
block_size = 256
n_embd = 128
n_layer = 4
ssm_d_state = 8
n_predict = 4
dropout = 0.0
bias = False
learning_rate = 6e-4
max_iters = 1000
weight_decay = 1e-1
beta1 = 0.9
beta2 = 0.95
grad_clip = 1.0
decay_lr = True
warmup_iters = 100
lr_decay_iters = 1000
min_lr = 6e-5
dtype = 'float32'
compile = False
eval_interval = 500
log_interval = 10
always_save_checkpoint = True
out_dir = 'out_stream'
# Patch + decayed horizons are on by default via model.py; to ablate set patch_factor=0
patch_factor = 0  # keep light test at byte-rate for backward-compat; set 4 for 4x context
